### ISSUE TITLE
README.md hyperlink ExternalSensor returns a 404 ERROR

### ISSUE THREAD

**Issue by BMC-Bruce** [openbmc/dbus-sensors#13]
[ExternalSensor](https://github.com/openbmc/docs/blob/master/designs/external-sensor.mdl) virtual sensor
returns a 404 ERROR.

Also note there already exists a [virtual-sensors.md](https://github.com/openbmc/docs/blob/master/designs/virtual-sensors.md)
in the [docs/design](https://github.com/openbmc/docs/tree/master/designs) folder.  Maybe _virtual sensor_, after ExternalSensor,
should have different wording.

**Comment by edtanous** [comment]
did this link get fixed?

**Comment by BMC-Bruce** [comment]
No, just check I still get 404 ERROR.

**Comment by BMC-Bruce** [comment]
I feel like this needs to be assigned to Josh Lehan Krellan, based off of when I found the issue.

**Comment by williamspatrick** [comment]
The issue is that the design was never merged in docs.  https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/41452  I just merged it so this can probably be closed.

**Comment by BMC-Bruce** [comment]
Thank you Patrick (and Josh for writing it), that does resolve this issue!
