### ISSUE TITLE
NVMeSensor Missing ObjectManager

### ISSUE THREAD

**Issue by iwoloschin** [openbmc/dbus-sensors#23]
The NVMeSensor daemon is missing an ObjectManager at `/xyz/openbmc_project/sensors`, it is instead incorrectly at `/xyz/openbmc_project/sensors/`. This results in no NVMe temperature sensors being available.

https://github.com/openbmc/dbus-sensors/blob/master/src/NVMeSensorMain.cpp#L235

I've tested removing the trailing `/` locally and it works on Micron 7450 NVMe drives I happened to have in my system. I do not have a CCLA signed yet so I can't technically submit a patch so this is the best I can do for the moment.

**Comment by amboar** [comment]
@iwoloschin please test https://gerrit.openbmc.org/c/openbmc/dbus-sensors/+/60299 and mark it as verified if it works for you.

**Comment by iwoloschin** [comment]
Thanks @amboar. I made the same patch locally last week before filing this bug and it resolved the issue.
