### ISSUE TITLE
ipmbsensor

### ISSUE THREAD

**Issue by GlobsGuo** [openbmc/dbus-sensors#9]
What is ipmbsensor ?
The ipmbsensor's source code gets the reading of ipmbsensor through DBus interface of ipmbbridge , so what is an ipmbsensor ? Does it actually exist ? I know the ipmbsensor is built on JSON configuration of entity-manager , but I can't understand why ipmbsensor's reading should be read by ipmbbridge's DBus interface .

**Comment by edtanous** [comment]
Please ask this question to the OpenBMC mailing list.

Most of your questions can be answered by reading through the source code for the exact mechanics of what an ipmb sensor does.
